Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Acyr/Acyr.Canary.mk2.phy.treefile XP_003247319_Acyrthosiphon_pis > Acyr.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Anoto/Anoto.Canary.mk2.phy.treefile Anotogastersieboldii_arthropsi > Anoto.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Asia/Asia.Canary.mk2.phy.treefile Asiagomphusmelaenops_arthropsi > Asia.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile BranchBel/BranchBel.Canary.mk2.phy.treefile BAC76024_Amphiop6_opsin_Branch > BranchBel.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile BranchFl/BranchFl.Canary.mk2.phy.treefile EEN42130_Amphiop6_BRAFLDRAFT_1 > BranchFl.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Capi124377/Capi124377.Canary.mk2.phy.treefile ELU16813_Capca1_124377_Capitel > Capi124377.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Capi54244/Capi54244.Canary.mk2.phy.treefile ELU03019_Capca1_54244_Capitell > Capi54244.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Crass18167/Crass18167.Canary.mk2.phy.treefile EKC18167_Rhodopsin_GQ-coupled_ > Crass18167.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Crass35173/Crass35173.Canary.mk2.phy.treefile EKC35173_Rhodopsin_partial_Cra > Crass35173.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Cupi/Cupi.Canary.mk2.phy.treefile CCP46951_arthropsin_Cupiennius > Cupi.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Dactylo/Dactylo.Canary.mk2.phy.treefile MZ277611_Dactylobiotus_arthrop > Dactylo.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Daph1/Daph1.Canary.mk2.phy.treefile EFX83617_arthropsin1_Daphnia_p > Daph1.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Daph2/Daph2.Canary.mk2.phy.treefile EFX83618_arthropsin2_Daphnia_p > Daph2.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Daph3/Daph3.Canary.mk2.phy.treefile EFX83619_arthropsin3_Daphnia_p > Daph3.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Daph4/Daph4.Canary.mk2.phy.treefile EFX83830_arthropsin4_Daphnia_p > Daph4.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Daph5/Daph5.Canary.mk2.phy.treefile EFX83831_arthropsin5_Daphnia_p > Daph5.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Daph6/Daph6.Canary.mk2.phy.treefile EFX84250_arthropsin6_Daphnia_p > Daph6.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Daph7/Daph7.Canary.mk2.phy.treefile EFX84031_arthropsin7_Daphnia_p > Daph7.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Daph8/Daph8.Canary.mk2.phy.treefile EFX84032_arthropsin8_Daphnia_p > Daph8.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Epio/Epio.Canary.mk2.phy.treefile Epiophlebiasuperstes_arthropsi > Epio.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Euperi/Euperi.Canary.mk2.phy.treefile CCP46948_arthropsin_Euperipato > Euperi.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Indolest/Indolest.Canary.mk2.phy.treefile Indolestesperegrinus_arthropsi > Indolest.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Ischnura/Ischnura.Canary.mk2.phy.treefile Ischnuraasiatica_arthropsin_LC > Ischnura.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Lottia154846/Lottia154846.Canary.mk2.phy.treefile Lotgi1_154846_Lottia_gigantea_ > Lottia15486.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Lottia156440/Lottia156440.Canary.mk2.phy.treefile Lotgi1_156440_Lottia_gigantea_ > Lottia156440.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Macrobio/Macrobio.Canary.mk2.phy.treefile MZ277610_Macrobiotus_arthropsi > Macrobio.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Macromia/Macromia.Canary.mk2.phy.treefile Macromiaamphigena_arthropsin_L > Macromia.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Mnais/Mnais.Canary.mk2.phy.treefile Mnaiscostalis_arthropsin_LC009 > Mnais.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Orthet/Orthet.Canary.mk2.phy.treefile Orthetrumalbistylum_arthropsin > Orthet.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile ParaMacro608/ParaMacro608.Canary.mk2.phy.treefile MZ277608_Paramacrobiotus_arthr > ParaMacro608.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Paramacro606/ParaMacro606.Canary.mk2.phy.treefile MZ277606_Paramacrobiotus_arthr > ParaMacro606.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Paramacro607/ParaMacro607.Canary.mk2.phy.treefile MZ277607_Paramacrobiotus_arthr > ParaMacro607.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Paramacro609/ParaMacro609.Canary.mk2.phy.treefile MZ277609_Paramacrobiotus_arthr > ParaMacro609.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Platy/Platy.Canary.mk2.phy.treefile AGL94565_r_opsin4_Platynereis_ > Platy.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Rama612/Rama612.Canary.mk2.phy.treefile MZ277612_Ramazzottius_arthrops > Rama612.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Rama613/Rama613.Canary.mk2.phy.treefile MZ277613_Ramazzottius_arthrops > Rama613.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Rama614/Rama614.Canary.mk2.phy.treefile MZ277614_Ramazzottius_arthrops > Rama614.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Somato/Somato.Canary.mk2.phy.treefile Somatochlorauchidai_arthropsin > Somato.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Sympet/Sympet.Canary.mk2.phy.treefile Sympetrumfrequens_arthropsin_L > Sympet.CanaryPackage.txt
Rscript AutomatedCanary.r Base/Arthropsins.2022.BaseTree.phy.treefile Tanyp/Tanyp.Canary.mk2.phy.treefile Tanypteryxpryeri_arthropsin_LC > Tanyp.CanaryPackage.txt
