args = commandArgs(trailingOnly=TRUE)
library(ape)
library(MonoPhy)
BaseTree <- read.tree(args[1])
CompareTree <- read.tree(args[2])
comparePhylo(BaseTree, CompareTree)
EditTree <- drop.tip(CompareTree, args[3])
Clades <- read.csv("CanaryClades.txt", header=FALSE)
NewOut <- c("AFZ78086_1_acropsin3_acropora_","aug_v2a_10282_t1_Acropora_digi","NV_CN151Suga08_1-24","NV_CN146Suga08_1-24")
#comparePhylo(BaseTree, EditTree, commons=FALSE, plot=TRUE)
#all.equal.phylo(BaseTree,EditTree, use.edge.length=FALSE)
RootedTree <- root(EditTree, outgroup=NewOut, resolve.root=TRUE)
AssessMonophyly(RootedTree, taxonomy=Clades)
