bash NovelPositionPackage.sh Acyr/Acyr.Canary.mk2.phy.treefile XP_003247319_Acyrthosiphon_pis > Acyr.NovelPosition.txt
bash NovelPositionPackage.sh Anoto/Anoto.Canary.mk2.phy.treefile Anotogastersieboldii_arthropsi > Anoto.NovelPosition.txt
bash NovelPositionPackage.sh Asia/Asia.Canary.mk2.phy.treefile Asiagomphusmelaenops_arthropsi > Asia.NovelPosition.txt
bash NovelPositionPackage.sh BranchBel/BranchBel.Canary.mk2.phy.treefile BAC76024_Amphiop6_opsin_Branch > BranchBel.NovelPosition.txt
bash NovelPositionPackage.sh BranchFl/BranchFl.Canary.mk2.phy.treefile EEN42130_Amphiop6_BRAFLDRAFT_1 > BranchFl.NovelPosition.txt
bash NovelPositionPackage.sh Capi124377/Capi124377.Canary.mk2.phy.treefile ELU16813_Capca1_124377_Capitel > Capi124377.NovelPosition.txt
bash NovelPositionPackage.sh Capi54244/Capi54244.Canary.mk2.phy.treefile ELU03019_Capca1_54244_Capitell > Capi54244.NovelPosition.txt
bash NovelPositionPackage.sh Crass18167/Crass18167.Canary.mk2.phy.treefile EKC18167_Rhodopsin_GQ-coupled_ > Crass18167.NovelPosition.txt
bash NovelPositionPackage.sh Crass35173/Crass35173.Canary.mk2.phy.treefile EKC35173_Rhodopsin_partial_Cra > Crass35173.NovelPosition.txt
bash NovelPositionPackage.sh Cupi/Cupi.Canary.mk2.phy.treefile CCP46951_arthropsin_Cupiennius > Cupi.NovelPosition.txt
bash NovelPositionPackage.sh Dactylo/Dactylo.Canary.mk2.phy.treefile MZ277611_Dactylobiotus_arthrop > Dactylo.NovelPosition.txt
bash NovelPositionPackage.sh Daph1/Daph1.Canary.mk2.phy.treefile EFX83617_arthropsin1_Daphnia_p > Daph1.NovelPosition.txt
bash NovelPositionPackage.sh Daph2/Daph2.Canary.mk2.phy.treefile EFX83618_arthropsin2_Daphnia_p > Daph2.NovelPosition.txt
bash NovelPositionPackage.sh Daph3/Daph3.Canary.mk2.phy.treefile EFX83619_arthropsin3_Daphnia_p > Daph3.NovelPosition.txt
bash NovelPositionPackage.sh Daph4/Daph4.Canary.mk2.phy.treefile EFX83830_arthropsin4_Daphnia_p > Daph4.NovelPosition.txt
bash NovelPositionPackage.sh Daph5/Daph5.Canary.mk2.phy.treefile EFX83831_arthropsin5_Daphnia_p > Daph5.NovelPosition.txt
bash NovelPositionPackage.sh Daph6/Daph6.Canary.mk2.phy.treefile EFX84250_arthropsin6_Daphnia_p > Daph6.NovelPosition.txt
bash NovelPositionPackage.sh Daph7/Daph7.Canary.mk2.phy.treefile EFX84031_arthropsin7_Daphnia_p > Daph7.NovelPosition.txt
bash NovelPositionPackage.sh Daph8/Daph8.Canary.mk2.phy.treefile EFX84032_arthropsin8_Daphnia_p > Daph8.NovelPosition.txt
bash NovelPositionPackage.sh Epio/Epio.Canary.mk2.phy.treefile Epiophlebiasuperstes_arthropsi > Epio.NovelPosition.txt
bash NovelPositionPackage.sh Euperi/Euperi.Canary.mk2.phy.treefile CCP46948_arthropsin_Euperipato > Euperi.NovelPosition.txt
bash NovelPositionPackage.sh Indolest/Indolest.Canary.mk2.phy.treefile Indolestesperegrinus_arthropsi > Indolest.NovelPosition.txt
bash NovelPositionPackage.sh Ischnura/Ischnura.Canary.mk2.phy.treefile Ischnuraasiatica_arthropsin_LC > Ischnura.NovelPosition.txt
bash NovelPositionPackage.sh Lottia154846/Lottia154846.Canary.mk2.phy.treefile Lotgi1_154846_Lottia_gigantea_ > Lottia15486.NovelPosition.txt
bash NovelPositionPackage.sh Lottia156440/Lottia156440.Canary.mk2.phy.treefile Lotgi1_156440_Lottia_gigantea_ > Lottia156440.NovelPosition.txt
bash NovelPositionPackage.sh Macrobio/Macrobio.Canary.mk2.phy.treefile MZ277610_Macrobiotus_arthropsi > Macrobio.NovelPosition.txt
bash NovelPositionPackage.sh Macromia/Macromia.Canary.mk2.phy.treefile Macromiaamphigena_arthropsin_L > Macromia.NovelPosition.txt
bash NovelPositionPackage.sh Mnais/Mnais.Canary.mk2.phy.treefile Mnaiscostalis_arthropsin_LC009 > Mnais.NovelPosition.txt
bash NovelPositionPackage.sh Orthet/Orthet.Canary.mk2.phy.treefile Orthetrumalbistylum_arthropsin > Orthet.NovelPosition.txt
bash NovelPositionPackage.sh ParaMacro608/ParaMacro608.Canary.mk2.phy.treefile MZ277608_Paramacrobiotus_arthr > ParaMacro608.NovelPosition.txt
bash NovelPositionPackage.sh Paramacro606/ParaMacro606.Canary.mk2.phy.treefile MZ277606_Paramacrobiotus_arthr > ParaMacro606.NovelPosition.txt
bash NovelPositionPackage.sh Paramacro607/ParaMacro607.Canary.mk2.phy.treefile MZ277607_Paramacrobiotus_arthr > ParaMacro607.NovelPosition.txt
bash NovelPositionPackage.sh Paramacro609/ParaMacro609.Canary.mk2.phy.treefile MZ277609_Paramacrobiotus_arthr > ParaMacro609.NovelPosition.txt
bash NovelPositionPackage.sh Platy/Platy.Canary.mk2.phy.treefile AGL94565_r_opsin4_Platynereis_ > Platy.NovelPosition.txt
bash NovelPositionPackage.sh Rama612/Rama612.Canary.mk2.phy.treefile MZ277612_Ramazzottius_arthrops > Rama612.NovelPosition.txt
bash NovelPositionPackage.sh Rama613/Rama613.Canary.mk2.phy.treefile MZ277613_Ramazzottius_arthrops > Rama613.NovelPosition.txt
bash NovelPositionPackage.sh Rama614/Rama614.Canary.mk2.phy.treefile MZ277614_Ramazzottius_arthrops > Rama614.NovelPosition.txt
bash NovelPositionPackage.sh Somato/Somato.Canary.mk2.phy.treefile Somatochlorauchidai_arthropsin > Somato.NovelPosition.txt
bash NovelPositionPackage.sh Sympet/Sympet.Canary.mk2.phy.treefile Sympetrumfrequens_arthropsin_L > Sympet.NovelPosition.txt
bash NovelPositionPackage.sh Tanyp/Tanyp.Canary.mk2.phy.treefile Tanypteryxpryeri_arthropsin_LC > Tanyp.NovelPosition.txt
